require("configs.completion.autopair")
require("configs.completion.cmp")
require("configs.core.options")
require("configs.core.keybinds")
require("configs.plugins")
require("configs.theme.theme")
require("configs.theme.higlights")
