vim.scriptencoding = 'utf-8'
vim.opt.encoding = 'utf-8'
vim.opt.fileencoding = 'utf-8'

vim.opt.wrap = false     -- wrap line code
vim.opt.number = true    -- show a list number
vim.opt.showmode = false -- show insert, visual or normal mode
vim.opt.hlsearch = true
vim.opt.showcmd = true
vim.opt.cmdheight = 0  -- height of statusline at the bottom
vim.opt.laststatus = 2 -- show where are you in file what
vim.opt.scrolloff = 0
vim.opt.shell = 'fish'
vim.opt.swapfile = false
vim.opt.expandtab = true
vim.opt.smarttab = true
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.breakindent = true
vim.opt.backspace = 'start,eol,indent'
vim.opt.list = true
vim.opt.fillchars:append({ eob = " " }) -- hide ~ character
